- hosts: all
  become: true
  tasks:
    - name: "Install httpd package"
      package:
        name: "httpd"
        state: present
      tags:
        - install
        - webserver

    - name: "Uninstall httpd package"
      package:
        name: "httpd"
        state: absent
      tags:
        - uninstall

    - name: "Copy webpages"
      copy:
        src: /home/ec2-user/index.html
        dest: /var/www/html
        owner: root
        group: root
      tags:
        - deploy
        - webserver

    - name: "Copy httpd configuration"
      copy:
        src: /home/ec2-user/httpd.conf
        dest: /etc/httpd/conf
      notify:
        - restart server
      tags:
        - config
        - webserver

  handlers:
    - name: "Restart server"
      service:
        name: httpd
        state: restarted
        enabled: yes
      tags:
        - restart
